# Use a lightweight Python image
FROM python:3.9-slim

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy project files into the Docker image
COPY . /app
WORKDIR /app

# Expose the port for Flask
EXPOSE 8080

# Command to run the Flask app
CMD ["python", "transform_news_main.py"]
